version: '3.1'

services:
    db:
        image: postgres:13.3
        restart: always
        container_name: 'modilap'
        environment:
            POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
            POSTGRES_DB: '${DATABASE_NAME}'
            TZ: America/Sao_Paulo

        ports:
            - 5432:5432
