version: '3.1'

services:
    db:
        image: postgres:13.3
        restart: always
        container_name: 'modilap'
        environment:
            POSTGRES_PASSWORD: process.env.APP_DB_PASSWORD
            POSTGRES_USER: process.env.APP_DB_USER
            POSTGRES_DB: process.env.APP_DB_NAME
