type User {
	increments: Int
	id: String
	token: String
	name: String
	email: String
	pwdhash: String
	created_at: String
	updated_at: String
}

input DataNotNull {
	name: String!
	email: String!
	pwdhash: String!
}

input Data {
	name: String
	email: String
	pwdhash: String
}

input DataLogin {
	email: String
	pwdhash: String
}

input IdOrEmail {
	id: Int
	email: String
}

type Query {
	# user(id: String!): User
	# users(limit: Int, offset: Int): [User]
	login(data: DataLogin): User
}

type Mutation {
	createUser(data: DataNotNull): User
	updateUser(id: String!, data: Data): User
	deleteUser(filter: IdOrEmail): Boolean
}
